"use client";
import {useMemo,useState} from "react"; import SpoilerControl from "../components/SpoilerControl"; import {useSpoilerChapter} from "@/lib/useSpoilerChapter"; import characters from "@/data/world/characters.json"; import pathways from "@/data/world/pathways.json"; import organizations from "@/data/world/organizations.json"; import locations from "@/data/world/locations.json"; import items from "@/data/world/items.json"; import lore from "@/data/world/lore.json";
type Tab="characters"|"pathways"|"organizations"|"locations"|"items"|"lore";
export default function WorldPage(){const [chapter]=useSpoilerChapter(1); const [tab,setTab]=useState<Tab>("characters"); const [q,setQ]=useState(""); const query=q.toLowerCase(); const tabs:Tab[]=["characters","pathways","organizations","locations","items","lore"];
 const generic=(arr:any[])=>arr.filter(x=>(x.spoilerChapter??x.firstMentionChapter??1)<=chapter && (!query||JSON.stringify(x).toLowerCase().includes(query)));
 const pathList=useMemo(()=>pathways.filter(p=>p.spoilerChapter<=chapter&&(!query||JSON.stringify(p).toLowerCase().includes(query))),[chapter,query]);
 return <main className="finalMain"><section className="compactHero"><p className="eyebrow">PHASE 4 · WORLD GRAPH</p><h1>World Graph</h1><p className="lead">A chapter-linked reference for the important Book 1 cast, all 22 standard pathways, organizations, locations, items and major lore entities.</p></section><SpoilerControl compact/><section className="filterBar"><label>Search world<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Amon, Door, Backlund, Sefirah…"/></label><div className="tabButtons">{tabs.map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t}</button>)}</div></section>
 {tab==="characters"&&<div className="worldGrid">{generic(characters).map((x:any)=><article key={x.id}><span>{x.group}</span><h2>{x.name}</h2><p>{x.role}</p><small>{x.pathway||"Non-pathway / unknown"} · first indexed Ch {x.firstMentionChapter}</small></article>)}</div>}
 {tab==="pathways"&&<div className="worldGrid pathwaysGrid">{pathList.map((p:any)=><article key={p.id}><span>PATHWAY</span><h2>{p.name}</h2><small>first indexed Ch {p.firstMentionChapter}</small><ol className="sequenceList">{p.sequences.filter((s:any)=>(s.firstMentionChapter??1431)<=chapter).map((s:any)=><li key={s.sequence}><b>S{s.sequence}</b><span>{s.name}</span><small>{s.firstMentionChapter?`known by Ch ${s.firstMentionChapter}`:"not explicitly indexed"}</small></li>)}</ol></article>)}</div>}
 {tab==="organizations"&&<div className="worldGrid">{generic(organizations).map((x:any)=><article key={x.id}><span>ORGANIZATION</span><h2>{x.name}</h2><p>{x.description}</p><small>first indexed Ch {x.firstMentionChapter}</small></article>)}</div>}
 {tab==="locations"&&<div className="worldGrid">{generic(locations).map((x:any)=><article key={x.id}><span>LOCATION</span><h2>{x.name}</h2><p>{x.description}</p><small>first indexed Ch {x.firstMentionChapter}</small></article>)}</div>}
 {tab==="items"&&<div className="worldGrid">{generic(items).map((x:any)=><article key={x.id}><span>MYSTICAL ITEM</span><h2>{x.name}</h2><p>{x.description}</p><small>first indexed Ch {x.firstMentionChapter}</small></article>)}</div>}
 {tab==="lore"&&<div className="worldGrid">{generic(lore).map((x:any)=><article key={x.id}><span>{x.kind}</span><h2>{x.name}</h2><p>{x.description}</p><small>first indexed Ch {x.firstMentionChapter}</small></article>)}</div>}
 </main>}
